blueprints/manage.py
from random import choice
from string import ascii_letters, digits

from charm.core.engine.util import objectToBytes
from cpabe_bsw07 import CPabe_BSW07
from charm.toolbox.pairinggroup import PairingGroup
from flask import Blueprint, render_template, request, g, redirect, url_for, session

from cpabe_rsa24 import CPabe_RSA24
from forms import UserInfoForm
from ormModels import ABEObjectsModel, db, UserModel, AttributesModel, AttributesMiddle, ResourceModel
from sqlalchemy import or_
import json
from os import remove

bp = Blueprint('manage', __name__, url_prefix='/manage')


@bp.before_request
def before_request():
    if g.user and g.user.is_admin == 1:
        pass
    else:
        return '不是管理员'


@bp.route('/')
def index():
    return render_template("manage.html")

@bp.route('/resource')
def resource():
    if request.method == 'GET':
        key_word = request.args.get('key_word')
        if key_word:
            resources = ResourceModel.query.filter(or_(
        ResourceModel.name.contains(key_word),
        ResourceModel.description.contains(key_word)
    )).all()
        else:
            resources = ResourceModel.query.all()
        return render_template('manage/resource.html', resources=resources)

@bp.route('/delete_resource/<string:resource_id>')
def delete_resource(resource_id):
    resource = ResourceModel.query.filter_by(id=resource_id).first()
    if resource:
        encf_path= 'storage/' + resource.id + '.enc'
        remove(encf_path)
        db.session.delete(resource)
        db.session.commit()
        return redirect(url_for('manage.resource'))
    return '资源不可访问'

@bp.route('/attribute')
def attribute():
    attributes = AttributesModel().query.all()
    return render_template("manage/attribute.html", attributes=attributes)


@bp.route('/add_attribute')
def add_attribute():
    name = ''.join([choice(ascii_letters + digits) for i in range(16)])
    attribute = AttributesModel(name=name)
    db.session.add(attribute)
    db.session.commit()
    return redirect(url_for('manage.attribute'))


@bp.route('/delete_attribute/<int:attribute_id>')
def delete_attribute(attribute_id):
    attribute = AttributesModel.query.get(attribute_id)
    db.session.delete(attribute)
    db.session.commit()
    return redirect(url_for('manage.attribute'))


@bp.route('/edit_attribute/<int:attribute_id>', methods=['GET', 'POST'])
def edit_attribute(attribute_id):
    if request.method == 'GET':
        attribute = AttributesModel.query.get(attribute_id)
        return render_template("manage/edit_attribute.html", attribute=attribute)
    else:
        attribute_name = request.form.get('attribute_name').upper()
        description = request.form.get('description').upper()
        attribute = AttributesModel.query.get(attribute_id)
        attribute.name = attribute_name
        attribute.description=description
        db.session.commit()
        return redirect(url_for('manage.attribute'))


@bp.route('/user')
def user():
    users = UserModel.query.all()
    return render_template("manage/user.html", users=users)


@bp.route('/add_user')
def add_user():
    name = ''.join([choice(ascii_letters + digits) for i in range(16)])
    users = UserModel(username=name, password='<PASSWORD>', email=name + '@qwe.qwe')
    db.session.add(users)
    db.session.commit()
    return redirect(url_for('manage.user'))


@bp.route('/delete_user/<int:user_id>')
def delete_user(user_id):
    user = UserModel.query.get(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('manage.user'))


@bp.route('/edit_user/<int:user_id>', methods=['GET', 'POST'])
def edit_user(user_id):
    if request.method == 'GET':
        user = UserModel.query.get(user_id)
        attributes_li = AttributesModel.query.all()
        return render_template("manage/edit_user.html", user=user, attributes_li=attributes_li)
    else:
        form = UserInfoForm(request.form)
        if form.validate():
            username = form.username.data
            email = form.email.data
        else:
            render_template('middle_page.html', message='数据格式错误',
                            url=url_for('manage.edit_user', user_id=user_id))
        attributes = request.form.keys()
        attributes_li = AttributesModel.query.all()
        user = UserModel.query.get(user_id)
        user.username = username
        user.email = email
        vali_attributes = [i.id for i in attributes_li if str(i.id) in attributes]
        cur_attributes = [i.id for i in user.attributes]
        for i in vali_attributes:
            if i not in cur_attributes:
                mid = AttributesMiddle(user_id=user_id, attribute_id=i)
                db.session.add(mid)
            else:
                cur_attributes.remove(i)
        for i in cur_attributes:
            if i not in vali_attributes:
                mid = AttributesMiddle.query.filter_by(user_id=user_id, attribute_id=i)
                mid.delete()
        db.session.commit()
        return redirect(url_for('manage.user'))


@bp.route('/change_user/<int:user_id>')
def change_user(user_id):
    user = UserModel.query.get(user_id)
    if user:
        session['user_id'] = user.id
        return render_template('middle_page.html', message='切换成功！', url=request.referrer)
    return render_template('middle_page.html', message='切换失败！', url=request.referrer)


@bp.route('/system')
def system():
    attributes=AttributesModel.query.all()
    return render_template('manage/system.html',attributes=attributes)


@bp.route('/init_system/<string:enc_type>')
def init_system(enc_type):
    if enc_type=='bsw07':
        pk = ABEObjectsModel.query.filter_by(name='07pk').first()
        if pk:
            return '已初始化，无需重复初始化'
        try:
            # instantiate a bilinear pairing map
            pairing_group = PairingGroup('SS512')
            # CP-ABE under DLIN (2-linear)
            cpabe = CPabe_BSW07(pairing_group)
            # run the set up
            (pk, msk) = cpabe.setup()
            pk_obj_bytes = objectToBytes(pk, pairing_group)
            msk_obj_bytes = objectToBytes(msk, pairing_group)
            pk_model = ABEObjectsModel(name='07pk', object_bytes=pk_obj_bytes)
            msk_model = ABEObjectsModel(name='07msk', object_bytes=msk_obj_bytes)
            db.session.add(pk_model)
            db.session.add(msk_model)
            db.session.commit()
            return '初始化成功'
        except Exception as e:
            return '算法初始化失败，检查charm crypto是否正常安装'
    elif enc_type=='rsa24':
        pk = ABEObjectsModel.query.filter_by(name='24pk').first()
        if pk:
            return '已初始化，无需重复初始化'
        cpabe = CPabe_RSA24()
        (pk, msk) = cpabe.setup()
        pk_obj_bytes = json.dumps(pk)
        msk_obj_bytes = json.dumps(msk)
        pk_model = ABEObjectsModel(name='24pk', object_bytes=pk_obj_bytes)
        msk_model = ABEObjectsModel(name='24msk', object_bytes=msk_obj_bytes)
        db.session.add(pk_model)
        db.session.add(msk_model)
        db.session.commit()
        return '初始化成功'
    else:
        return '不支持的加密方案'

@bp.route('/set_base')
def set_base():
    name=request.args.get('name')
    nbase = AttributesModel.query.filter_by(name=name).first()
    if nbase:
        obase = AttributesModel.query.filter_by(is_base=True).first()
        if obase:
            obase.is_base = False
        nbase.is_base = True

        db.session.commit()
        return redirect(request.referrer)
    else:
        return '属性不存在'

blueprints/user.py
from random import choice
from re import match
from string import ascii_letters, digits

from flask import Blueprint, request, render_template, redirect, session, url_for, jsonify
from flask_mail import Message
from werkzeug.security import generate_password_hash, check_password_hash

from forms import SignupForm, LoginForm
from ormModels import db, UserModel, mail, EmailCaptchaModel

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/')
def index():
    return render_template('user.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('user/login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
        else:
            return render_template('user/login.html', show='show', title='登录失败', msg='账号或密码不合规')
        user = UserModel.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            return render_template('middle_page.html', message='登录成功！', url=url_for('index'))
        return render_template('user/login.html', show='show', title='登录失败', msg='账号或密码错误')


@bp.route('/logout')
def logout():
    session['user_id'] = None
    return redirect(url_for('user.login'))


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('user/signup.html')
    else:
        form = SignupForm(request.form)
        # code=request.form.get('verifycode')
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return render_template('middle_page.html', message='注册成功！请登录。', url=url_for('user.login'))
        return render_template('user/signup.html', show='show', title='注册失败', msg='注册失败，检查信息是否有误')


@bp.route('/sendCode', methods=['POST'])
def sendCode():
    email = request.json.get('email')
    if not match(r"^[a-zA-Z0-9_]{4,20}@(163|126|gmail|qq|outlook)\.com", email):
        return jsonify({"code": 400, "msg": "邮箱不合规"})
    # 邮箱是否注册
    user = UserModel.query.filter_by(email=email).first()
    if user:
        return jsonify({"code": 400, "msg": "邮箱已被注册"})
    captcha = EmailCaptchaModel.query.filter_by(email=email).first()
    if captcha:
        return jsonify({"code": 400, "msg": "验证码已存在"})
    # 生成验证码
    captcha = ''.join([choice(ascii_letters + digits) for i in range(6)])
    message = Message(subject='注册验证码', recipients=[email], body=f'您的验证码是:{captcha}', charset='utf-8')
    mail.send(message)
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({"code": 200, "msg": "发送成功"})

@bp.route('/user_list')
def user_list():
    key_word = request.args.get('key_word')
    if key_word:
        users = UserModel.query.filter(UserModel.username.contains(key_word)).all()
    else:
        users=UserModel.query.all()
    return render_template('user/user_list.html', users=users)

@bp.route('/check_user/<int:id>')
def check_user(id):
    user=UserModel.query.get(id)
    if user:
        return render_template('user/profile.html',user=user)
    else:
        return '用户不存在'

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>资源访问控制系统</title>
    <link rel="stylesheet" href="/static/fontawesome5/css/all.min.css">
    <link rel="stylesheet" href="/static/bootstrap5/css/bootstrap.min.css">
    <script src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <style>
        .main-content {
            padding: 5px;
        }

        .main-content2 {
            border: 2px solid #555555;
            border-radius: 5px;
            height: 100%;
            overflow: hidden;
        }

        iframe {
            width: 100%;
            height: 100%;
        }

        html,
        body {
            min-height: 100vh;
            margin: 0;
            padding: 0;
            background-color: rgb(79, 79, 79);
        }

        .sidebar-ground {
            background-color: #2c2e2f;
        }

        .sidebar-ground div,
        .sidebar-ground button {
            width: 100%;
        }

        .sidebar-ground button {
            background-color: rgba(0, 0, 0, 0);
            border: 0;
            border-bottom: 1px solid rgb(84, 84, 84);
            padding: 10px;
            color: rgb(171, 171, 171);
        }

        .sidebar-ground button:hover {
            color: rgb(243, 243, 243);
        }

        #sidebarMenu>button {
            font-size: 20px;
        }

    </style>
</head>

<body class="d-flex flex-column">

    <!-- 导航栏 -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" style="height: 40px" href="#">
                <img src="/static/photos/Beacon.png" style="height: 100%">
                <span>Beacon</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {{ kzt }}" href="{{ url_for('manage.index') }}"><i class="fa fa-wrench"></i> 控制台</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ zy }}" href="{{ url_for('resource.index') }}"><i class="fa fa-folder"></i> 资源</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ yh }}" href="{{ url_for('user.index') }}"><i class="fa fa-user"></i> 用户</a>
                    </li>
                </ul>
                <div class="d-flex align-items-center">
                    <a class="navbar-text me-2" href="{{ url_for('user.logout') }}">退出登录</a>
                    <img src="/static/avatars/SCY.png" alt="User Avatar"
                        class="rounded-circle me-2" style="width: 32px;">
                    <button class="navbar-text btn btn-link" onclick="change_page('{{ url_for('user.check_user',id=g.user.id) }}')">{{ g.user.username }}</button>
                </div>
            </div>
        </div>
    </nav>

    <div class="container-fluid flex-grow-1 d-flex flex-column">
        <div class="row flex-grow-1">
            <!-- 侧边栏 -->
            <div class="col-md-2 sidebar-ground">
                <p></p>
                <div class="card bg-dark">
                    <img src="/static/photos/Beacon.png" style="width: 60%;margin: 10px auto">
                    <h1 style="text-align: center;color: #e5e5e5">Beacon</h1>
                </div>
                <p></p>
                <div class="btn-group-vertical" id="sidebarMenu">
                    {% block menu %}{% endblock %}
                </div>
            </div>
            <!-- 主要内容 -->
            <div class="col-md-10 main-content">
                <div class="main-content2"><iframe id="show_window" src=""></iframe></div>
            </div>
        </div>
    </div>
<script>
    function change_page(page_url){
        document.getElementById('show_window').src=page_url;
    }
</script>
</body>

</html>

templates/manage.html
{% extends 'base.html' %}
{% set kzt='active' %}
{% block menu %}

    <button class="collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#userFunctions">
        <i class="fas fa-database"></i>
        资源管理
    </button>
    <div id="userFunctions" class="collapse" data-bs-parent="#sidebarMenu">
        <div class="btn-group-vertical">
            <button type="button" onclick="change_page('{{ url_for('manage.resource') }}')"><i class="fa fa-search"></i> 资源管理</button>
        </div>
    </div>

    <button class="collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#systemFunctions">
        <i class="fas fa-server"></i>
        系统管理
    </button>
    <div id="systemFunctions" class="collapse" data-bs-parent="#sidebarMenu">
        <div class="btn-group-vertical">
            <button type="button" onclick="change_page('{{ url_for('manage.attribute') }}')"><i
                    class="fa fa-address-card"></i> 属性管理
            </button>
            <button type="button" onclick="change_page('{{ url_for('manage.user') }}')"><i class="fa fa-users-cog"></i>
                用户管理
            </button>
            <button type="button" onclick="change_page('{{ url_for('manage.system') }}')"><i class="fa fa-cog"></i> 系统管理</button>
        </div>
    </div>
{% endblock %}

templates/middle_page.html
<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <title>通用中间页</title>
  <style>
    .message {
      text-align: center;
      margin-top: 200px;
      font-size: 30px;
    }
    .tips{
      text-align: center;
      margin-top: 50px;
      font-size: 10px;
    }
  </style>
  <script>
    var countdown=2;
    var timer=setInterval(function () {
        countdown -= 1;
        document.getElementById('timer').innerText=countdown;
        // 倒计时结束的时候执行
        if (countdown <= 0) {
            // 清掉定时器
            clearInterval(timer);
            window.location.href = "{{ url }}";
        }

    }, 1000);
  </script>
</head>
<body style="background-color: white">
  <div class="message">
    <span>{{ message }}</span>
  </div>
<div class="tips">
    <span id="timer">2</span><span>秒后自动跳转</span>
</div>
</body>
</html>

templates/resource.html
{% extends 'base.html' %}
{% set zy='active' %}
{% block menu %}

    <button class="collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#userFunctions">
        <i class="fas fa-arrow-up"></i>
        上传资源
    </button>
    <div id="userFunctions" class="collapse" data-bs-parent="#sidebarMenu">
        <div class="btn-group-vertical">
            <button type="button" onclick="change_page('{{ url_for('resource.upload_file') }}')"><i class="fa fa-upload"></i> 上传文件</button>
            <button type="button" onclick="change_page('{{ url_for('resource.upload_text') }}')"><i class="fa fa-file-upload"></i> 上传文本</button>
        </div>
    </div>
    <button class="collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#viewsource">
        <i class="fas fa-box-open"></i>
        管理资源
    </button>
    <div id="viewsource" class="collapse" data-bs-parent="#sidebarMenu">
        <div class="btn-group-vertical">
            <button type="button" onclick="change_page('{{ url_for('resource.search_resource') }}')"><i class="fa fa-search"></i> 检索资源</button>
            <button type="button" onclick="change_page('{{ url_for('resource.my_resource') }}')"><i class="fa fa-file-alt"></i> 我的资源</button>
            <button type="button" onclick="change_page('{{ url_for('resource.favorites') }}')"><i class="fa fa-star"></i> 我的收藏</button>
        </div>
    </div>
{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% set yh='active' %}
{% block menu %}

    <button class="collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#userFunctions">
        <i class="fas fa-database"></i>
        用户查询
    </button>
    <div id="userFunctions" class="collapse" data-bs-parent="#sidebarMenu">
        <div class="btn-group-vertical">
            <button type="button" onclick="change_page('{{ url_for('user.user_list') }}')"><i class="fa fa-search"></i> 用户查询</button>
        </div>
    </div>

{% endblock %}