blueprints/resource.py
import json
import random
from io import BytesIO
from os import remove
from uuid import uuid4

from charm.core.engine.util import objectToBytes, bytesToObject
from charm.toolbox.pairinggroup import PairingGroup, GT
from flask import Blueprint, render_template, request, g, send_file, url_for, redirect, current_app

from aes import encrypt_file, decrypt_file, encrypt_bytes
from cpabe_bsw07 import CPabe_BSW07
from cpabe_rsa24 import CPabe_RSA24
from ormModels import AttributesModel, ABEObjectsModel, ResourceModel, db, FavoritesMiddle
from sqlalchemy import or_

bp = Blueprint('resource', __name__, url_prefix='/resource')
enc_types=['bsw07','rsa24']

@bp.before_request
def before_request():
    if g.user:
        pass
    else:
        return '未登录'


@bp.route('/')
def index():
    return render_template('resource.html')


@bp.route('/upload_file', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'GET':
        attributes = AttributesModel.query.all()
        return render_template('resource/upload_file.html', attributes=attributes)
    else:
        file = request.files.get('file')
        description = request.form.get('description')
        policy = request.form.get('policy').strip()
        encrypt_type=request.form.get('encrypt_type')
        if policy:
            lc = policy.count('(')
            rc = policy.count(')')
            if lc!=rc:
                return '不合法的访问结构'
            if current_app.config['USE_BASE']:
                base_attr = AttributesModel.query.filter_by(is_base=True).first().name
                if base_attr:
                    policy = base_attr + ' and (' + policy + ')'
        else:
            if current_app.config['USE_BASE']:
                base_attr = AttributesModel.query.filter_by(is_base=True).first().name
                if base_attr:
                    policy = base_attr
        if file and (encrypt_type in enc_types):
            if encrypt_type=='bsw07':
                # 取公共参数
                pk = ABEObjectsModel.query.filter_by(name='07pk').first()
                if not pk:
                    raise Exception('系统未初始化')
                # 准备加密算法
                pairing_group = PairingGroup('SS512')
                cpabe = CPabe_BSW07(pairing_group)
                pk = bytesToObject(pk.object_bytes, pairing_group)
                # 加密对称密钥
                msg = pairing_group.random(GT)
                msgbytes = objectToBytes(msg, pairing_group)
                c = cpabe.encrypt(pk, msg, policy)
                cbytes = objectToBytes(c, pairing_group)
            else:
                # 取公共参数
                pk = ABEObjectsModel.query.filter_by(name='24pk').first().object_bytes
                if not pk:
                    raise Exception('系统未初始化')
                # 准备加密算法
                cpabe = CPabe_RSA24()
                pk = json.loads(pk)
                # 加密对称密钥
                msg = random.randint(0,2^512)
                msgbytes = msg.to_bytes(512,byteorder='big')
                c = cpabe.encrypt(pk, msg, policy)
                cbytes = json.dumps(c).encode('utf8')
            # 对称加密文件
            encid = uuid4().hex
            encname = 'storage/' + encid + '.enc'
            encrypt_file(file, encname, msgbytes)
            file_resource = ResourceModel(id=encid, name=file.filename, file_path=encname, policy=policy,
                                          abe_cipher=cbytes, description=description, resource_type='file',
                                          owner=g.user, encrypt_type=encrypt_type)
            db.session.add(file_resource)
            db.session.commit()
            return render_template('middle_page.html', url=url_for('resource.search_resource'),
                                   message='上传加密成功')
        else:
            return '请选择文件，指定访问结构'


@bp.route('upload_text', methods=['GET', 'POST'])
def upload_text():
    if request.method == 'GET':
        attributes = AttributesModel.query.all()
        return render_template('resource/upload_text.html',attributes=attributes)
    else:
        text = request.form.get('text')
        description = request.form.get('description')
        policy = request.form.get('policy').strip()
        name = request.form.get('name')
        encrypt_type = request.form.get('encrypt_type')
        if policy:
            lc = policy.count('(')
            rc = policy.count(')')
            if lc!=rc:
                return '不合法的访问结构'
            if current_app.config['USE_BASE']:
                base_attr = AttributesModel.query.filter_by(is_base=True).first().name
                if base_attr:
                    policy = base_attr + ' and (' + policy + ')'
        else:
            if current_app.config['USE_BASE']:
                base_attr = AttributesModel.query.filter_by(is_base=True).first().name
                if base_attr:
                    policy = base_attr
        if text and name and (encrypt_type in enc_types):
            if encrypt_type == 'bsw07':
                # 取公共参数
                pk = ABEObjectsModel.query.filter_by(name='07pk').first()
                if not pk:
                    raise Exception('系统未初始化')
                # 准备加密算法
                pairing_group = PairingGroup('SS512')
                cpabe = CPabe_BSW07(pairing_group)
                pk = bytesToObject(pk.object_bytes, pairing_group)
                # 加密对称密钥
                msg = pairing_group.random(GT)
                msgbytes = objectToBytes(msg, pairing_group)
                c = cpabe.encrypt(pk, msg, policy)
                cbytes = objectToBytes(c, pairing_group)
            else:
                # 取公共参数
                pk = ABEObjectsModel.query.filter_by(name='24pk').first().object_bytes
                if not pk:
                    raise Exception('系统未初始化')
                # 准备加密算法
                cpabe = CPabe_RSA24()
                pk = json.loads(pk)
                # 加密对称密钥
                msg = random.randint(0, 2 ^ 512)
                msgbytes = msg.to_bytes(512, byteorder='big')
                c = cpabe.encrypt(pk, msg, policy)
                cbytes = json.dumps(c).encode('utf8')
            # 对称加密文件
            encid = uuid4().hex
            encname = 'storage/' + encid + '.enc'
            encbytes = encrypt_bytes(text.encode('utf8'), msgbytes)
            with open(encname, 'wb') as file:
                file.write(encbytes)
            file_resource = ResourceModel(id=encid, name=name, file_path=encname, policy=policy,
                                          abe_cipher=cbytes, description=description, resource_type='text',
                                          owner=g.user,encrypt_type=encrypt_type)
            db.session.add(file_resource)
            db.session.commit()
            return render_template('middle_page.html', url=url_for('resource.search_resource'),
                                   message='上传加密成功')
        else:
            return '请输入名称、文件内容，指定访问结构'


@bp.route('/search_resource')
def search_resource():
    if request.method == 'GET':
        key_word = request.args.get('key_word')
        if key_word:
            resources = ResourceModel.query.filter(or_(
        ResourceModel.name.contains(key_word),
        ResourceModel.description.contains(key_word)
    )).all()
        else:
            resources = ResourceModel.query.all()
        return render_template('resource/search_resource.html', resources=resources)


@bp.route('/get_resource/<string:resource_id>')
def get_resource(resource_id):
    resource = ResourceModel.query.filter_by(id=resource_id).first()
    if resource is None:
        return '资源不存在'
    if resource.encrypt_type=='bsw07':
        pk = ABEObjectsModel.query.filter_by(name='07pk').first()
        msk = ABEObjectsModel.query.filter_by(name='07msk').first()
        if not (pk and msk):
            raise Exception('系统未初始化')
        pairing_group = PairingGroup('SS512')
        cpabe = CPabe_BSW07(pairing_group)
        pk = bytesToObject(pk.object_bytes, pairing_group)
        msk = bytesToObject(msk.object_bytes, pairing_group)
        attributes = [attribute.name for attribute in g.user.attributes]
        secret_key = cpabe.keygen(pk, msk, attributes)
        cbytes = resource.abe_cipher
        c = bytesToObject(cbytes, pairing_group)
        msg = cpabe.decrypt(pk, secret_key, c)
        if not msg:
            return render_template('middle_page.html', url=url_for('resource.search_resource'),
                                   message='属性不符合访问结构')
        msgbytes = objectToBytes(msg, pairing_group)
    else:
        pk = ABEObjectsModel.query.filter_by(name='24pk').first()
        msk = ABEObjectsModel.query.filter_by(name='24msk').first()
        if not (pk and msk):
            raise Exception('系统未初始化')
        cpabe = CPabe_RSA24()
        pk = json.loads(pk.object_bytes)
        msk = json.loads(msk.object_bytes)
        attributes = [attribute.name for attribute in g.user.attributes]
        secret_key = cpabe.keygen(pk, msk, attributes)
        cbytes = resource.abe_cipher
        c = json.loads(cbytes.decode('utf8'))
        msg = cpabe.decrypt(pk, secret_key, c)
        if not msg:
            return render_template('middle_page.html', url=url_for('resource.search_resource'),
                                   message='属性不符合访问结构')
        msgbytes = msg.to_bytes(512, byteorder='big')
    file = decrypt_file(resource.file_path, msgbytes)
    if resource.resource_type == 'file':
        response = send_file(
            BytesIO(file),  # 使用BytesIO包装bytes数据
            as_attachment=True,  # 告诉浏览器这应该作为一个附件下载
            attachment_filename=resource.name,  # 设定下载时显示的文件名
            mimetype='application/octet-stream'  # 或根据实际文件类型设定mimetype
        )
        return response
    else:
        text = file.decode('utf8')
        return render_template('resource/show_text.html', text=text)


@bp.route('/my_resource')
def my_resource():
    resources = ResourceModel.query.filter_by(owner=g.user)

blueprints/user.py
from random import choice
from re import match
from string import ascii_letters, digits

from flask import Blueprint, request, render_template, redirect, session, url_for, jsonify
from flask_mail import Message
from werkzeug.security import generate_password_hash, check_password_hash

from forms import SignupForm, LoginForm
from ormModels import db, UserModel, mail, EmailCaptchaModel

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/')
def index():
    return render_template('user.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('user/login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
        else:
            return render_template('user/login.html', show='show', title='登录失败', msg='账号或密码不合规')
        user = UserModel.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            session['user_id'] = user.id
            return render_template('middle_page.html', message='登录成功！', url=url_for('index'))
        return render_template('user/login.html', show='show', title='登录失败', msg='账号或密码错误')


@bp.route('/logout')
def logout():
    session['user_id'] = None
    return redirect(url_for('user.login'))


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('user/signup.html')
    else:
        form = SignupForm(request.form)
        # code=request.form.get('verifycode')
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return render_template('middle_page.html', message='注册成功！请登录。', url=url_for('user.login'))
        return render_template('user/signup.html', show='show', title='注册失败', msg='注册失败，检查信息是否有误')


@bp.route('/sendCode', methods=['POST'])
def sendCode():
    email = request.json.get('email')
    if not match(r"^[a-zA-Z0-9_]{4,20}@(163|126|gmail|qq|outlook)\.com", email):
        return jsonify({"code": 400, "msg": "邮箱不合规"})
    # 邮箱是否注册
    user = UserModel.query.filter_by(email=email).first()
    if user:
        return jsonify({"code": 400, "msg": "邮箱已被注册"})
    captcha = EmailCaptchaModel.query.filter_by(email=email).first()
    if captcha:
        return jsonify({"code": 400, "msg": "验证码已存在"})
    # 生成验证码
    captcha = ''.join([choice(ascii_letters + digits) for i in range(6)])
    message = Message(subject='注册验证码', recipients=[email], body=f'您的验证码是:{captcha}', charset='utf-8')
    mail.send(message)
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({"code": 200, "msg": "发送成功"})

@bp.route('/user_list')
def user_list():
    key_word = request.args.get('key_word')
    if key_word:
        users = UserModel.query.filter(UserModel.username.contains(key_word)).all()
    else:
        users=UserModel.query.all()
    return render_template('user/user_list.html', users=users)

@bp.route('/check_user/<int:id>')
def check_user(id):
    user=UserModel.query.get(id)
    if user:
        return render_template('user/profile.html',user=user)
    else:
        return '用户不存在'

templates/user/login-signup-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>登录页面</title>
    <link rel="stylesheet" href="/static/bootstrap5/css/bootstrap.min.css">
    <script src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <style>
        html, body {
            height: 100%;
        }

        .login-form {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
            background-color: rgba(0, 0, 0, 0.4);
        }

        input {
            background-color: rgba(0, 0, 0, 0.4) !important;
        }

        video {
            position: fixed;
            right: 0;
            bottom: 0;
            min-width: 100%;
            min-height: 100%;
            width: auto;
            height: auto;
            z-index: -9999;
            /*灰色调*/
            /*-webkit-filter:grayscale(100%)*/

        }

        .element {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 300px; /* 自定义宽度 */
            height: 150px; /* 自定义高度 */
        }

    </style>
</head>
<body class="d-flex flex-column justify-content-center">
<video autoplay muted loop poster="/static/photos/loginPic.png" style="width: 100%">
    <source src="https://scycree.oss-cn-beijing.aliyuncs.com/loginVideo.mp4">
</video>

<div class="toast element {{ show }}">
    <div class="toast-header justify-content-between">
        {{ title }}
        <button type="button" class="btn-close" data-bs-dismiss="toast"></button>
    </div>
    <div class="toast-body">
        {{ msg }}
    </div>
</div>

<div class="container-fluid">
    <div class="row justify-content-end">
        <div class="col-md-6">
            <div class="card login-form">
                <div class="card-body">
                    <h4 class="text-center">
                        <a class="text-light" href="{{ url_for('user.login') }}">登录</a>
                        <span class="text-light">/</span>
                        <a class="text-light" href="{{ url_for('user.signup') }}">注册</a>
                    </h4>
                    {% block form %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>

templates/user/login.html
{% extends 'user/login-signup-base.html' %}
{% block form%}
<form method="post">
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label text-light">邮箱</label>
        <input type="email" class="form-control text-light" name="email" id="exampleInputEmail1"
               aria-describedby="emailHelp" required>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label text-light">密码</label>
        <input type="password" class="form-control text-light" name="password"
               id="exampleInputPassword1" required>
    </div>
    <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary">登录</button>
    </div>
</form>
{% endblock %}

templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/fontawesome5/css/all.min.css">
    <link rel="stylesheet" href="/static/bootstrap5/css/bootstrap.min.css">
    <script src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <style>
        .head-bar{
    height: 40px;
    width: auto;
}
.infobox{
    width: 800px;
    min-height: 800px;
    margin: 0 auto;
    background-color: #fcfcfc;
    box-shadow:2px 2px 5px #aaaaaa;
    border-radius: 50px;
    margin-bottom: 60px;
}
.basicbox{
    height: 120px;
    position: relative;
}
.head-frame{
    width: 128px;
    height: 128px;
    margin-left: 20px;
    position: absolute;
    top: -20px;
}
.hover-txt{
    border: 0;
    position: absolute;
    top: 35%;
    width: 100%;
    height: 30%;
    text-align: center;
    font-size: 150%;
    color: #ffffff;
    background-color: rgba(203, 203, 203, 0.25);
    display: none;
}
#cgimg{
    display: none;
}
.head-img{
    width: 128px;
    height: 128px;
    border-radius: 30px;
    border: 3px solid #b7b7b7;

}
.basic-info{
    width: 550px;
    height: 120px;
    position: absolute;
    left: 200px;
}
.uname{
    font-size: 40px;
    font-weight: 500;
    color: #4d4d4d;
}
.resource-info{
    height: 30px;
    margin-bottom: 5px;
    font-size: 20px;
}
.info-key{
    color: #868686;
}
.info-value{
    color: #4d4d4d;
    font-weight: bolder;
}
.info-sp{
    border: #d5d5d5 solid 1px;
    margin: 0 10px;
}
.join-time{
    font-size: 16px;
}
.resource_box{
    width: 700px;
    margin: 15px auto;
    border-top: 2px solid #bdbdbd;
    padding: 10px;
}
.follow{
    margin-left: 15px;
    color: darkblue;
    font-weight: bolder;
    font-size: 16px;
    cursor: pointer;
}

.follow:hover{
    text-decoration: underline;
    color: blue;
}

.follow-li{
    margin-left: 15px;
    color: #868686;
}

.follow-li:hover{
    text-decoration: underline;
    color: darkblue;
}
    </style>
</head>
<body>
<div class="head-bar"></div>
    <div class="infobox">
        <div class="basicbox">
            <div class="head-frame">
                <img alt="用户头像" class="head-img" src="/static/avatars/SCY.png" >
            </div>
            <div class="basic-info">
                <span class="uname">{{ user.username }}</span>
                <span>uid: {{ user.id }}</span>
                <div class="resource-info">
                    <span class="info-key">资源: </span><span class="info-value">{{ user.resources|length }}</span>
                    <span class="info-sp"></span>
                    <span class="info-key">属性: </span>
                    <span class="info-value">{{ user.attributes|length }}</span>
                </div>
                <div class="join-time">
                    <span class="info-key">加入时间: </span>
                    <span class="info-value">{{ user.join_time }}</span>
                </div>
            </div>
        </div>

        <div class="resource_box">
            <span class="info-key">Ta发布的资源:</span>
            <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th scope="col">资源名</th>
            <th scope="col">类型</th>
            <th scope="col">描述</th>
            <th scope="col">加密方案</th>
            <th scope="col">访问结构</th>
            <th scope="col">上传者</th>
            <th scope="col">操作</th>
            <th scope="col">上传时间</th>
        </tr>
        </thead>
        <tbody>
        {% for resource in user.resources %}
        <tr>
            <td>{{ resource.name }}</td>
            <td>{{ resource.resource_type }}</td>
            <td>{{ resource.description }}</td>
            <td>{{ resource.encrypt_type }}</td>
             <td>{{ resource.policy }}</td>
             <td>{{ resource.owner.username }}</td>
            <td style="padding: 5px;width: 85px">
                <button type="button" class="btn btn-sm btn-success" onclick="change_page('{{ url_for('resource.get_resource',resource_id=resource.id) }}')"><i class="fa fa-download"></i></button>
                <button type="button" class="btn btn-sm btn-warning text-light" onclick="change_page('{{ url_for('resource.favorite_resource',resource_id=resource.id) }}')"><i class="fa fa-star"></i></button>

            </td>
        <td>{{ resource.upload_time }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
<script>
    function change_page(page_url){
        document.location.href=page_url;
    }
</script>
</body>
</html>

templates/user/signup.html
{% extends 'user/login-signup-base.html' %}
{% block form %}
    <form method="post">
        <div class="mb-3">
            <label for="username" class="form-label text-light">用户名</label>
            <input type="text" id="username" class="form-control text-light" name="username" required>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label text-light">邮箱</label>
            <input type="email" class="form-control text-light" name="email" id="exampleInputEmail1"
                   aria-describedby="emailHelp" required>
        </div>
        <div class="mb-3">
            <label for="verifycode" class="form-label text-light">验证码</label>
            <div class="input-group">
                <input type="text" maxlength="6" id="captcha" class="form-control text-light" name="captcha"
                       required>
                <button type="button" id="sendcodebutton" class="btn btn-outline-success" onclick="sendCode();">
                    发送验证码
                </button>
            </div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label text-light">密码</label>
            <input type="password" class="form-control text-light" name="password"
                   id="exampleInputPassword1" required>
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary">注册</button>
        </div>
    </form>
    <script>
        function sendCode() {
            var email = document.getElementById('exampleInputEmail1').value;
            fetch("/user/sendCode", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    email: email
                })
            }).then(function (res) {
                if (res.status === 200) {
                    return res.json()
                } else {
                    alert('服务器状态异常，请稍后再试')
                    return null
                }
            }).then(function (data){
                if (data['code']==200){
               var btn = document.getElementById('sendcodebutton');
                    var countdown = 60;
                    // 开始倒计时之前，就取消按钮的点击事件
                    btn.disabled = true;
                    var timer = setInterval(function () {
                        btn.innerText = countdown;
                        countdown -= 1;
                        // 倒计时结束的时候执行
                        if (countdown <= 0) {
                            // 清掉定时器
                            clearInterval(timer);
                            // 将按钮的文字重新修改回来
                            btn.innerText = "发送验证码";
                            // 重新绑定点击事件
                            btn.disabled = false;
                        }

                    }, 1000)}
                else {
                    alert(data['msg'])
                }
            }).catch(function (err) {
                console.log(err);
            });
        }
    </script>
{% endblock %}

templates/user/user_list.html
{% extends 'manage/table-base.html' %}
{% set page_name='用户列表' %}
{% block table %}
    <form class="form-range mb-3" style="width: 40%">
        <div class="input-group">
        <input type="text" class="form-control" name="key_word"
               required>
        <button class="btn btn-success">
            搜索
        </button>
    </div>
    </form>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th scope="col">用户名</th>
            <th scope="col">加入时间</th>
            <th scope="col">属性</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td><a href="{{ url_for('user.check_user',id=user.id) }}" class="text">{{ user.username }}</a></td>
            <td>{{ user.join_time }}</td>
            <td style="padding: 0;"><select class="form-select">
            {% for attribute in user.attributes %}
                  <option>{{attribute.name}}</option>
            {% endfor %}
            </select>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}